<?php

/**
 * Implementation of hook_menu().
 */
function path_redirect_tools_menu() {
  $items['admin/build/path-redirect/tools'] = array(
    'title' => 'Tools',
    'access arguments' => array('administer redirects'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('path_redirect_tools_admin_settings_form'),
    'file' => 'path_redirect_tools.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );
  
  $items['admin/build/path-redirect/tools/settings'] = array(
    'title' => 'Settings',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 0,
  );
  
  $items['admin/build/path-redirect/tools/import'] = array(
    'title' => 'Import redirects',
    'description' => 'Import URL redirects.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('path_redirect_tools_form'),
    'access arguments' => array('administer redirects'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'path_redirect_tools.admin.inc',
    'weight' => 2,
  );

  $items['admin/build/path-redirect/tools/transmogrify'] = array(
    'title' => 'URL aliases report',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('path_redirect_tools_report_form'),
    'access arguments' => array('administer redirects'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'path_redirect_tools.admin.inc',
    'weight' => 3,
  );

  $items['admin/build/path-redirect/tools/export'] = array(
    'title' => 'Export all redirects',
    'page callback' => 'path_redirect_tools_export',
    'access arguments' => array('administer redirects'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'path_redirect_tools.admin.inc',
    'weight' => 4,
  );
  
  $items['admin/build/path-redirect/tools/delete'] = array(
    'title' => 'Delete all redirects',
    'description' => 'Delete every single URL redirect.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('path_redirect_tools_massdelete_form'),
    'access arguments' => array('administer redirects'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'path_redirect_tools.admin.inc',
    'weight' => 5,
  );

  return $items;
}